version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cp ./configs/$CONFIG_NAME ./active-config.yml  # Copy selected config

  build:
    commands:
      - echo "Deploying using $CONFIG_NAME"
      - chmod +x ./deploy.sh
      - ./deploy.sh -c active-config.yml
