version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - export AWS_DEFAULT_REGION=us-east-1
      - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq
      - cp ./configs/$CONFIG_NAME ./active-config.yml

  build:
    commands:
      - echo "Deploying using $CONFIG_NAME"
      - chmod +x ./deploy.sh
      - ./deploy.sh -c active-config.yml
