apptags:
  department: ops
  product: ptrwebsite
  environment: prod
  service: webui
git:
  repo: https://github.com/ptrsoft/ptr-website.git
  tag:  main
general:
  rebuild-stack: false
  domain: ptrtechnology.com
  subdomain: web
  hostedzoneid: Z06401662L0WAGUZJFQOF
  onlyupdate: false
  purestaticpages: true

