version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq

      # Fetch AWS credentials from Secrets Manager
      - echo "Fetching AWS credentials from Secrets Manager"
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id deploymentSecret --query SecretString --output text)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r .AWS_SECRET_ACCESS_KEY)

      - cp ./configs/$CONFIG_NAME ./active-config.yml

  build:
    commands:
      - echo "Deploying using $CONFIG_NAME"
      - chmod +x ./deploy.sh
      - ./deploy.sh -c active-config.yml
