apiVersion: v1
kind: Secret
metadata:
  name: smoke-aws-credentials
type: Opaque
stringData:
  credentials: |-
    [dev]
    aws_access_key_id     = AKIAZQ3DTYESDZ5A4KH7
    aws_secret_access_key = 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

    [default]
    aws_access_key_id     = AKIAZQ3DTYESDZ5A4KH7
    aws_secret_access_key = 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
  config: |-
    [profile dev]
    region = us-east-1
    output = json
    [default]
    region = us-east-1
