apptags:
  department: ops
  product: ptrcloud
  environment: prod
  service: ui
git:
  repo: https://github.com/ptrsoft/ptr-standalone-ui.git
  tag:  main
general:
  organization: promodeagro
  rebuild-stack: false
  domain: ptrtechnology.com
  subdomain: ptrcloud
  hostedzoneid: Z06401662L0WAGUZJFQOF
  onlyupdate: true
  purestaticpages: false
  apexdomain: yes

