apptags:
  department: ptrtechnology
  product: papumewebsite
  environment: prod
  service: ui
git:
  repo: https://github.com/ptrsoft/flender-demo.git
  tag:  main
general:
  organization: ptr
  rebuild-stack: false
  domain: papu.me
  subdomain: 
  hostedzoneid:
  onlyupdate: false
  purestaticpages: false
  apexdomain: yes

