apptags:
  department: promodeagro
  product: images
  environment: prod
  service: ui
git:
  repo: https://github.com/promodeagro/promodeagro-products-images.git
  tag:  main
general:
  organization: promodeagro
  rebuild-stack: false
  domain: promodeagro.com
  subdomain: images
  hostedzoneid: Z00062013820EO6BYULDB
  onlyupdate: true
  purestaticpages: true
  apexdomain: no

