AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - CloudFront with Header Security and site content
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  DomainName:
    Description: Main domain
    Type: String
  SubDomain:
    Description: Subdomain
    Type: String
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String
  CDNDomain:
    Description: Domain Name of CDN
    Type: String

Resources:
  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Adding Record in ptrtechnology.com
      HostedZoneId: !Ref 'HostedZoneId'
      RecordSets:
      - Name: !Sub '${SubDomain}.${DomainName}'
        Type: 'A'
        AliasTarget:
        # This zoneid is amazon specified, hardcode it
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !Ref 'CDNDomain'

Outputs:
  Website:
    Description: Website address
    Value: !Sub '${SubDomain}.${DomainName}'
